# Generated by Django 5.1.7 on 2025-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_order_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="client_name",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="Client Name"
            ),
        ),
    ]
